name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      platform: aws
      region: us-east-1
      account: 222222222222

    steps:
      - name: Mostrar mensaje
        run: echo "Holas"


  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Install AWS CLI
        run: sudo pip install awscli


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWSKEY }}
          aws-secret-access-key: ${{ secrets.AWSPASS }}
          aws-region: us-east-1

      - name: Build with SAM
        run: sam build --use-container

      - name: Deploy with SAM
        run: |
          sam deploy --stack-name prueba-app1 --region us-east-1 --no-fail-on-empty-changeset --no-confirm-changeset --save-params --capabilities CAPABILITY_IAM 

